const {chromium}=require('@playwright/test'),assert=require('node:assert/strict');
function overlap(a,b){for(const poly of [a,b])for(let i=0;i<poly.length;i++){const p=poly[i],q=poly[(i+1)%poly.length],axis=[q[1]-p[1],p[0]-q[0]],project=v=>v[0]*axis[0]+v[1]*axis[1],aa=a.map(project),bb=b.map(project);if(Math.max(...aa)<Math.min(...bb)||Math.max(...bb)<Math.min(...aa))return false;}return true;}
(async()=>{const browser=await chromium.launch({args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1280,height:800}});let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>localStorage.setItem('apex.settings',JSON.stringify({quality:'low',sound:false,device:'touch'})));await page.goto('http://localhost:8080');await page.waitForFunction(()=>apexDebug.test);
for(let index=0;index<5;index++){await page.click('#track-card');await page.click(`[data-track="${index}"]`);const {samples,footprints}=await page.evaluate(()=>apexDebug.test.road());let checks=0;for(let i=0;i<samples.length-1;i++){const a=samples[i],b=samples[i+1],point=(s,n)=>[s.p[0]+s.n[0]*n,s.p[1]+s.n[1]*n],quad=[point(a,-10.3),point(a,10.3),point(b,10.3),point(b,-10.3)];for(const poly of footprints){assert(!overlap(quad,poly),`track ${index}, segment ${i} has obstructing scenery`);checks++;}}console.log(`PASS circuit ${index+1}: all 1800 road/kerb segments clear (${checks} footprint checks)`);}
await page.click('#start');await page.click('#brief-start');await page.waitForFunction(()=>apexDebug.snapshot().state==='race',null,{timeout:60000});
await page.keyboard.press('e');assert(await page.evaluate(()=>apexDebug.test.input().ers));await page.keyboard.press('e');assert(!await page.evaluate(()=>apexDebug.test.input().ers));
await page.locator('[data-control="ers"]').click();assert(await page.evaluate(()=>apexDebug.test.input().ers));await page.keyboard.press('e');
await page.evaluate(()=>{window.fakePad={connected:true,axes:[0],buttons:Array.from({length:10},()=>({pressed:false,value:0}))};Object.defineProperty(navigator,'getGamepads',{value:()=>[fakePad]});fakePad.buttons[0].pressed=true;apexDebug.test.input();fakePad.buttons[0].pressed=false;apexDebug.test.input()});assert(await page.evaluate(()=>apexDebug.test.input().ers));
await page.keyboard.down('ArrowRight');assert((await page.evaluate(()=>apexDebug.test.input().steer))<0);await page.keyboard.up('ArrowRight');await page.keyboard.down('ArrowLeft');assert((await page.evaluate(()=>apexDebug.test.input().steer))>0);await page.keyboard.up('ArrowLeft');
await page.keyboard.press('Escape');assert(!await page.evaluate(()=>apexDebug.snapshot().raw.ers));assert.equal(await page.locator('[data-action="pause"] svg rect').count(),2);console.log('PASS keyboard/touch/gamepad ERS latch, pause reset and driver-left/right mapping');
await page.evaluate(()=>{apexDebug.test.pose(100,0);apexDebug.test.advance(.4,{});apexDebug.test.advance(1,{brake:1})});assert.equal(await page.evaluate(()=>apexDebug.snapshot().car.gear),-1);assert((await page.evaluate(()=>apexDebug.snapshot().car.u))<0);

await page.click('#resume');await page.waitForFunction(()=>document.querySelector('#gear').textContent==='R');console.log('PASS reverse motion and R dashboard in scene');for(const size of [{width:1280,height:800},{width:390,height:844},{width:844,height:390}]){await page.setViewportSize(size);let map=await page.locator('#minimap').boundingBox(),dash=await page.locator('#dash').boundingBox();assert(dash.y>=map.y+map.height);assert(dash.x>size.width/2);assert(dash.x+dash.width<=size.width);assert(dash.y+dash.height<=size.height);}
await page.setViewportSize({width:1280,height:800});await page.screenshot({path:'/home/user/apex-3.0.1-race.png'});console.log('PASS dashboard right beneath minimap on desktop, portrait and landscape');assert.deepEqual(errors,[]);await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
