import assert from 'node:assert/strict';
import {createCar,stepCar,validateLayout} from '../physics.js';
import {aeroForces,combinedForces,CAR} from '../js/physics/models.js';
const env={width:18,setup:.5,assist:'simulation',aeroZone:false};
const input={steer:0,throttle:1,brake:0,ers:false,aero:false};
function run(c,seconds,i=input,e=env){for(let n=0;n<seconds*120;n++)stepCar(c,i,1/120,e);return c;}
let a=run(createCar(),10),b=run(createCar(),10);assert.deepEqual(a,b);assert(a.v>40&&a.v<100);assert(Math.abs(a.wx)<.001);console.log('PASS deterministic straight-line acceleration',a.v*3.6);
a=createCar();b=createCar();run(a,4,{...input,steer:.4});run(b,4,{...input,steer:-.4});assert(a.heading>0&&b.heading<0);assert(Math.abs(a.wx+b.wx)<.01);assert(a.wx>0);console.log('PASS left/right symmetry and front-steered yaw',a.heading,a.wx);
a=run(createCar(),12);b=structuredClone(a);run(a,3,{...input,ers:true});run(b,3);assert(a.v>b.v+1);assert(a.energy<b.energy);console.log('PASS ERS power increases speed',a.v-b.v);
a=createCar();a.energy=0;run(a,1,{...input,ers:true});assert.equal(a.deployKW,0);console.log('PASS empty ERS no boost');
a=run(createCar(),10);run(a,1,{...input,aero:true});assert(!a.aeroOpen);run(a,1,{...input,aero:true},{...env,aeroZone:true});assert(a.aeroOpen&&a.aeroAngle>.9);run(a,.1,{...input,aero:true,brake:1},{...env,aeroZone:true});assert(!a.aeroOpen);console.log('PASS aero zone rejection, deployment, brake closure');
let parts=createCar().parts;let f=aeroForces(30,.5,parts,0),g=aeroForces(60,.5,parts,0),h=aeroForces(60,.5,parts,1);assert(Math.abs(g.total/f.total-4)<1e-9);assert(h.drag<g.drag&&h.rear<g.rear);console.log('PASS v² aero and open-flap coefficient reductions');
for(let i=0;i<100;i++){let f=combinedForces(i*40,i*60,2000);assert(Math.hypot(...f)<2000.001)}console.log('PASS combined friction bound');
a=run(createCar(),8);let v=a.v;run(a,2,{...input,throttle:0,brake:1});assert(a.v<v/2);console.log('PASS stable braking');
a=run(createCar({fuel:5}),6);b=run(createCar({fuel:100}),6);assert(a.v>b.v);console.log('PASS fuel mass affects acceleration');
a=run(createCar(),5);a.fuel=0;v=a.v;run(a,1);assert(a.v<v);console.log('PASS out-of-fuel engine cut');
a=run(createCar(),6);a.pitRemaining=12;run(a,12.1);assert.equal(a.pitRemaining,0);assert(a.lapTime>18);console.log('PASS timed pit service');
assert(validateLayout({x:{x:.5,y:.5,size:1,opacity:1,hidden:false}}));assert(!validateLayout({x:{x:4}}));console.log('PASS layout validation');
a=createCar();let temp=a.wheels[0].temp;run(a,1,{...input,throttle:0});assert(a.wheels[0].temp<temp&&a.wheels[0].temp>65);assert(a.wheels[0].brakeTemp>200);console.log('PASS thermal integration retains heat without timestep collapse');
a=run(createCar(),8);b=structuredClone(a);run(a,1.4,{...input,throttle:0,brake:1},env);run(b,1.4,{...input,throttle:0,brake:1},{...env,wet:true});assert(b.v>a.v);console.log('PASS wet slicks increase braking distance');
