import assert from 'node:assert/strict';
import {createCar,stepCar} from '../physics.js';
import {TimingGaps,cornerAssist,speedProfile} from '../js/race-assist.js';
function run(brake,throttle=0,level=.5,energy=1000){const c=createCar();c.u=c.v=45;c.gear=c.lastGear=4;c.energy=energy;c.brake=brake;c.throttle=throttle;let recovered=0;for(let i=0;i<60;i++){stepCar(c,{brake,throttle},1/120,{engineBraking:level});recovered+=c.regenKW/120;}assert(Math.abs(c.energy-energy-recovered)<1e-6);return c;}
const light=run(.1),heavy=run(.7),coast=run(0),gas=run(0,1),full=run(0,0,.5,4000),low=run(0,0,0),high=run(0,0,1);
assert(heavy.energy>light.energy&&light.energy>1000);assert(coast.energy>1000&&coast.u<45);assert.equal(gas.energy,1000);assert.equal(full.energy,4000);assert(high.u<low.u&&high.energy>low.energy);assert(heavy.regenKW<=110);console.log('PASS stronger brake recovery, loaded coast recovery, engine setting, full-battery and full-throttle limits');
let stopped=createCar();stopped.energy=100;for(let i=0;i<120;i++)stepCar(stopped,{},1/120);assert.equal(stopped.energy,100);
const clock=new TimingGaps();clock.update('a',0,0);clock.update('b',0,2);clock.update('a',100,4);clock.update('b',100,6);assert.equal(clock.gap({name:'a',total:100},{name:'b',total:100},1000),'+2.000s');assert.equal(clock.gap({name:'a',total:2100},{name:'b',total:100},1000),'+2 LAP');assert.equal(clock.gap({name:'unknown',total:100},{name:'b',total:100},1000),'—');clock.update('b',0,7);clock.update('b',100,8);assert.equal(clock.gap({name:'a',total:100},{name:'b',total:100},1000),'+2.000s');console.log('PASS shared timing-gate interpolation, lapped display, unavailable timing and reverse recrossing');
const points=Array.from({length:361},(_,i)=>({x:100*Math.cos(i*Math.PI/180),z:100*Math.sin(i*Math.PI/180)})),p=speedProfile(points,200*Math.PI),car={s:0,v:60,u:60,direction:1};let a=cornerAssist(p,car,{throttle:1,brake:0});assert(a.active&&a.input.throttle===0&&a.input.brake>0);assert(!cornerAssist(p,car,{throttle:1},false).active);assert(!cornerAssist(p,{...car,direction:-1},{brake:1}).active);assert(cornerAssist(p,car,{},true,.5).target<a.target);for(let i=0;i<p.speeds.length;i++)assert(p.speeds[i]**2<=p.speeds[(i+1)%p.speeds.length]**2+14*p.ds+.001);console.log('PASS corner-speed envelope, circular braking bound, wet reduction, assist off/reverse bypass');
