import {speedProfile,cornerAssist,TimingGaps} from './js/race-assist.js';
import {roadClear} from './js/road-clearance.js';
import * as THREE from './vendor/three.module.js';
import {tracks} from './data/tracks.js';
import {createModel,animateModel} from './js/vehicle/model.js';
import {clamp,approach,createCar,stepCar,validateLayout} from './physics.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const store={get(k,d){try{return JSON.parse(localStorage.getItem('apex.'+k))??d}catch{return d}},set(k,v){try{localStorage.setItem('apex.'+k,JSON.stringify(v))}catch{toast('Storage unavailable. Changes last for this session.')}}};
let toastTimer;function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
const touchCap=navigator.maxTouchPoints>0, defaults={device:touchCap?'touch':'keyboard',autoBrake:true,engineBraking:.5,sound:true,volume:.25,quality:'low',assist:'casual',compound:'medium',startFuel:25,brakeBias:.57,pressure:22,rideHeight:.06,ersMode:'manual',steering:'buttons',deadzone:.12,sensitivity:1,tiltSensitivity:1,tiltDeadzone:3,tiltInvert:false,highContrast:false,largeUI:false,display:'windowed',transmission:'auto',color:'#d5ff43',setup:.5,profile:'Default',autoLandscape:false};
let settings={...defaults,...store.get('settings',{})};
const defaultBindings={throttle:['ArrowUp','KeyW'],brake:['ArrowDown','KeyS'],left:['ArrowLeft','KeyA'],right:['ArrowRight','KeyD'],ers:['KeyE'],aero:['Space'],up:['ShiftLeft'],down:['ControlLeft'],camera:['KeyC'],look:['KeyB'],pause:['Escape'],reset:['KeyR'],pit:['KeyP'],map:['KeyM'],hud:['KeyH'],transmission:['KeyG'],autoBrake:['KeyV']};
let bindings={...defaultBindings,...store.get('bindings',defaultBindings)};if(!bindings||Object.keys(defaultBindings).some(k=>!Array.isArray(bindings[k])||bindings[k].some(v=>typeof v!=='string')))bindings=structuredClone(defaultBindings);
const labels={throttle:'Throttle',brake:'Brake',left:'Steer left',right:'Steer right',ers:'ERS',aero:'Active aero',up:'Upshift',down:'Downshift',camera:'Camera',look:'Look back',pause:'Pause',reset:'Reset to track',pit:'Pit service',map:'Track map',hud:'HUD',transmission:'Auto / manual transmission',autoBrake:'Corner brake assist'};
let records=store.get('records.v3',{}),state='menu',page='race',cameraMode=0,trackIndex=0,car=createCar(),bots=[],raceTime=0,countdown=0,accumulator=0,pausedFrom='race',lastFrame=performance.now(),renderTime=0,editing=false,editSnapshot,selectedControl='throttle',rebind=null;
let touchInputs={},keys=new Set(),lastDevice=settings.device,filtered={steer:0,throttle:0,brake:0,ers:false,aero:false},raw={...filtered},padEnabled=true,tilt={live:false,last:0,value:0,neutral:0,seen:0},fps=60;

let curve,length,roadWidth=18,trackGroup=new THREE.Group(),carPaint=[],carModel,opponents=[],samples=[],sceneryFootprints=[],raceProfile,timing=new TimingGaps(),brakeGuide={target:0,active:false};
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas:$('#scene'),antialias:false,powerPreference:'high-performance'});}catch(e){$('#fatal').classList.remove('hidden');$('#fatal').textContent='WebGL is unavailable. Enable hardware acceleration or try a current browser to drive APEX LINE.';throw e;}
renderer.setPixelRatio(Math.min(devicePixelRatio,settings.quality==='low'?.7:settings.quality==='medium'?1:settings.quality==='ultra'?1.75:1.35));renderer.shadowMap.enabled=['high','ultra'].includes(settings.quality);renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
const scene=new THREE.Scene();scene.background=new THREE.Color('#a2b7bd');scene.fog=new THREE.Fog('#a2b7bd',180,1100);
const camera=new THREE.PerspectiveCamera(46,1,.1,2200);const hemi=new THREE.HemisphereLight('#e5f5ff','#535c30',2.5);scene.add(hemi);const sun=new THREE.DirectionalLight('#fff0ce',3);sun.position.set(-60,150,90);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-50;sun.shadow.camera.right=50;sun.shadow.camera.top=50;sun.shadow.camera.bottom=-50;scene.add(sun);scene.add(sun.target);
const mat=(color,roughness=.65,metalness=.1)=>new THREE.MeshStandardMaterial({color,roughness,metalness});
function box(w,h,d,material,x=0,y=0,z=0,parent){let o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),material);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent?.add(o);return o}
const black=mat('#101510',.8),rubber=mat('#121412',.98),metal=mat('#414840',.4,.6),white=mat('#e9ecde'),lime=mat(settings.color,.29,.5);
function makeCar(color=lime){return createModel(color)}
carModel=makeCar(lime,true);scene.add(carModel);scene.add(trackGroup);
function buildTrack(){while(trackGroup.children.length){let c=trackGroup.children[0];c.traverse(o=>{o.geometry?.dispose();if(o.material?.map)o.material.map.dispose();});trackGroup.remove(c);}
 let t=tracks[trackIndex];let pts=t.shape.map(([x,z])=>new THREE.Vector3(x,0,z));let initial=new THREE.CatmullRomCurve3(pts,true,'centripetal',.45),scale=1;pts.forEach(p=>p.multiplyScalar(scale));curve=new THREE.CatmullRomCurve3(pts,true,'centripetal',.45);length=curve.getLength();samples=[];const count=1800;
 for(let i=0;i<=count;i++){let u=(i%count)/count,p=curve.getPointAt(u),tangent=curve.getTangentAt(u),normal=new THREE.Vector3(tangent.z,0,-tangent.x);samples.push({p,tangent,normal});}
 const ground=box(8000,.3,8000,mat(t.theme==='desert'?'#b8a074':t.theme==='coast'?'#8b9c96':'#536443'),0,-.25,0,trackGroup);ground.receiveShadow=true;
 function strip(inner,outer,material,y=.02,alternate=false){let pos=[],colors=[],color=new THREE.Color();for(let i=0;i<count;i++){let a=samples[i],b=samples[i+1];for(let [s,d]of[[a,inner],[a,outer],[b,inner],[b,inner],[a,outer],[b,outer]]){pos.push(s.p.x+s.normal.x*d,y,s.p.z+s.normal.z*d);if(alternate){color.set(Math.floor(i/3)%2?'#e9eddf':'#d95840');colors.push(color.r,color.g,color.b);}}}let geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));if(alternate)geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();material.side=THREE.DoubleSide;let mesh=new THREE.Mesh(geo,material);mesh.receiveShadow=true;trackGroup.add(mesh);}
 strip(-15,15,mat('#8c917a'),.005);strip(-9,9,mat('#414741'),.03);strip(-9,-8.8,white,.042);strip(8.8,9,white,.042);for(let side of [-1,1])strip(side*9,side*10.3,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.9,side:THREE.DoubleSide}),.045,true);
 let barrierMat=mat('#b7bdae');for(let i=0;i<count;i+=5){let a=samples[i],b=samples[Math.min(i+5,count)],dist=a.p.distanceTo(b.p);for(let side of [-1,1]){let pos=a.p.clone().add(b.p).multiplyScalar(.5).addScaledVector(a.normal,side*18);if(!roadClear(samples,pos.x,pos.z,Math.hypot(.35,dist+1)/2))continue;let block=box(.35,.8,dist+1,barrierMat,pos.x,.4,pos.z,trackGroup);block.rotation.y=Math.atan2(a.tangent.x,a.tangent.z);}}
 // Original low-poly landscape, seeded deterministic positions.
 let randState=719;function rand(){randState=(randState*16807)%2147483647;return(randState-1)/2147483646}
 const leaf=mat('#33492d');for(let i=0;i<(t.theme==='desert'?20:150);i++){let a=samples[Math.floor(rand()*count)],side=rand()>.5?1:-1,d=40+rand()*160,p=a.p.clone().addScaledVector(a.normal,side*d),h=6+rand()*10;let tree=new THREE.Mesh(new THREE.ConeGeometry(h*.35,h,5),leaf);tree.position.set(p.x,h/2,p.z);if(roadClear(samples,p.x,p.z,h*.35*Math.SQRT2))trackGroup.add(tree);}
 for(let i=0;i<9;i++){let a=samples[(i*91+35)%count],p=a.p.clone().addScaledVector(a.normal,30);if(!roadClear(samples,p.x,p.z,Math.hypot(15,38)/2))continue;let stand=box(12,5,35,mat(i%2?'#b5b8a7':'#646f5d'),p.x,2.5,p.z,trackGroup);stand.rotation.y=Math.atan2(a.tangent.x,a.tangent.z);let roof=box(15,.4,38,mat('#272e28'),p.x,6,p.z,trackGroup);roof.rotation.y=stand.rotation.y;}
 const a=samples[0];let gate=new THREE.Group();gate.position.copy(a.p);gate.rotation.y=Math.atan2(a.tangent.x,a.tangent.z);box(.6,7,.6,metal,-12,3.5,0,gate);box(.6,7,.6,metal,12,3.5,0,gate);box(25,2,.6,black,0,7,0,gate);let signCanvas=document.createElement('canvas');signCanvas.width=1024;signCanvas.height=128;let ctx=signCanvas.getContext('2d');ctx.fillStyle='#151a13';ctx.fillRect(0,0,1024,128);ctx.fillStyle='#d5ff43';ctx.font='bold italic 68px Arial';ctx.textAlign='center';ctx.fillText('APEX LINE  /  START',512,88);let sign=new THREE.Mesh(new THREE.PlaneGeometry(24,2),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(signCanvas),side:THREE.DoubleSide}));sign.position.set(0,7,-.32);sign.rotation.y=Math.PI;gate.add(sign);if([-1,1].every(side=>roadClear(samples,a.p.x+a.normal.x*12*side,a.p.z+a.normal.z*12*side,.43,10.5)))trackGroup.add(gate);
 for(let j=0;j<18;j++)for(let k=0;k<2;k++){let p=a.p.clone().addScaledVector(a.normal,j-8.5).addScaledVector(a.tangent,k);let sq=box(1,.015,1,(j+k)%2?black:white,p.x,.06,p.z,trackGroup);sq.rotation.y=gate.rotation.y;}
 for(let zone of t.aeroZones){for(let [u,label,col] of [[zone.start,'AERO','#d5ff43'],[zone.end,'CLOSE','#ff7457']]){let a=trackAt(u*length);let canvas=document.createElement('canvas');canvas.width=256;canvas.height=128;let ctx=canvas.getContext('2d');ctx.fillStyle='#121912';ctx.fillRect(0,0,256,128);ctx.fillStyle=col;ctx.font='bold 48px Arial';ctx.textAlign='center';ctx.fillText(label,128,84);let sign=new THREE.Mesh(new THREE.PlaneGeometry(4,2),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(canvas),side:THREE.DoubleSide}));sign.position.copy(a.p).addScaledVector(a.n,12);sign.position.y=2;sign.rotation.y=Math.atan2(-a.t.x,-a.t.z);if(roadClear(samples,sign.position.x,sign.position.z,2,10.5))trackGroup.add(sign);}}
 for(let o of opponents)scene.remove(o);opponents=[];for(let color of ['#f3f0df','#f76747','#60b3d7','#a88fd0','#ffcb55']){let o=makeCar(color);scene.add(o);opponents.push(o);}raceProfile=speedProfile(samples.map(a=>a.p),length);resetBots();batchTrack();}
function batchTrack(){
 trackGroup.updateMatrixWorld(true);sceneryFootprints=[];
 trackGroup.traverse(o=>{if(!o.isMesh)return;o.geometry.computeBoundingBox();const b=o.geometry.boundingBox,world=new THREE.Box3().copy(b).applyMatrix4(o.matrixWorld);if(world.max.y<.1||world.min.y>3)return;sceneryFootprints.push([[-1,-1],[1,-1],[1,1],[-1,1]].map(([x,z])=>{const p=new THREE.Vector3(x<0?b.min.x:b.max.x,0,z<0?b.min.z:b.max.z).applyMatrix4(o.matrixWorld);return [p.x,p.z]}));});
 let groups=new Map();trackGroup.traverse(o=>{if(!o.isMesh)return;let key=o.material.uuid;if(!groups.has(key))groups.set(key,{material:o.material,geos:[]});let g=o.geometry.index?o.geometry.toNonIndexed():o.geometry.clone();g.applyMatrix4(new THREE.Matrix4().copy(trackGroup.matrixWorld).invert().multiply(o.matrixWorld));groups.get(key).geos.push(g);});
 trackGroup.clear();for(let {material,geos}of groups.values()){let geometry=new THREE.BufferGeometry();for(let attr of Object.keys(geos[0].attributes)){if(!geos.every(g=>g.attributes[attr]))continue;let size=geos.reduce((n,g)=>n+g.attributes[attr].array.length,0),arr=new Float32Array(size),offset=0;for(let g of geos){arr.set(g.attributes[attr].array,offset);offset+=g.attributes[attr].array.length}geometry.setAttribute(attr,new THREE.BufferAttribute(arr,geos[0].attributes[attr].itemSize));}let mesh=new THREE.Mesh(geometry,material);mesh.receiveShadow=true;trackGroup.add(mesh);geos.forEach(g=>g.dispose());}
}
function trackAt(s){let u=((s%length)+length)%length/length;let p=curve.getPointAt(u),t=curve.getTangentAt(u),n=new THREE.Vector3(t.z,0,-t.x);return{p,t,n};}
function curvature(s){let a=trackAt(s),b=trackAt(s+8);return Math.atan2(a.t.z*b.t.x-a.t.x*b.t.z,a.t.dot(b.t))/8;}
function place(model,s,x=0){let a=trackAt(s);model.position.copy(a.p).addScaledVector(a.n,x);model.rotation.y=Math.atan2(-a.t.x,-a.t.z);return a;}
function resetBots(){bots=opponents.map((o,i)=>({name:['M. REYES','S. KATO','L. MOREAU','A. COSTA','J. PARK'][i],s:20+i*17,total:20+i*17,x:(i%2?1:-1)*3,v:0}));}
buildTrack();
function resize(){let r=$('#scene').getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();if(editing||state!=='menu')renderTouch();}
window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);document.addEventListener('fullscreenchange',resize);resize();
function saveSettings(){store.set('settings',settings);applySettings()}
function applySettings(){document.body.classList.toggle('high-contrast',settings.highContrast);document.body.classList.toggle('large-ui',settings.largeUI);document.body.classList.toggle('immersive',settings.display==='immersive');document.body.classList.toggle('cinematic',settings.display==='cinematic');renderer.setPixelRatio(Math.min(devicePixelRatio,settings.quality==='low'?.7:settings.quality==='medium'?1:settings.quality==='ultra'?1.75:1.35));renderer.shadowMap.enabled=['high','ultra'].includes(settings.quality);lime.color.set(settings.color);$('#device-name').textContent=({keyboard:'Keyboard',gamepad:'Gamepad',touch:'Touch controls',tilt:'Tilt + touch'})[settings.device]||'Keyboard';$('#device-symbol').textContent=settings.device==='keyboard'?'⌨':settings.device==='gamepad'?'⊞':'◎';$('#launch-hint').textContent=settings.device==='keyboard'?'WASD / ARROW KEYS TO DRIVE':'YOUR CONTROLS. YOUR RACING LINE.';$('#transmission').value=settings.transmission;$('#aero-setup').value=settings.setup*100;$('#aero-output').textContent=settings.setup<.35?'Low drag':settings.setup>.65?'High grip':'Balanced';resize();}
applySettings();$('#capability').textContent=touchCap?'TOUCH READY · WEBGL ONLINE':'KEYBOARD READY · WEBGL ONLINE';
function switchPage(p){page=p;$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===p));$('#race-config').classList.toggle('hidden',p!=='race');$('#garage').classList.toggle('hidden',p!=='garage');$('#records').classList.toggle('hidden',p!=='records');if(p==='records')renderRecords();}
$$('[data-page]').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));
$$('[data-color]').forEach(b=>b.onclick=()=>{settings.color=b.dataset.color;saveSettings();toast('Livery saved')});$('#aero-setup').oninput=e=>{settings.setup=Number(e.target.value)/100;saveSettings()};$('#transmission').onchange=e=>{settings.transmission=e.target.value;saveSettings()};
$('#track-card').onclick=showTracks;refreshTrackCard();
function formatTime(t){if(!Number.isFinite(t))return '—';let min=Math.floor(t/60),sec=t%60;return `${String(min).padStart(2,'0')}:${sec.toFixed(3).padStart(6,'0')}`;}
function renderRecords(){let list=$('#records-list');list.replaceChildren();let found=false;for(let [k,v] of Object.entries(records)){if(typeof v!=='number'||!Number.isFinite(v))continue;found=true;let row=document.createElement('div');row.className='record-row';let name=document.createElement('span'),time=document.createElement('b');name.textContent=k;time.textContent=formatTime(v);row.append(name,time);list.append(row);}if(!found)list.innerHTML='<p class="info">A clean lap is a blank canvas. Complete your first lap to set a personal best.<br>Off-track laps are not saved. Records stay in this browser.</p>';}
$('#clear-records').onclick=()=>{if(confirm('Clear all personal lap records on this browser?')){records={};store.set('records.v3',records);renderRecords()}};
async function fullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();return;}if(!document.documentElement.requestFullscreen)throw Error();await document.documentElement.requestFullscreen();if(settings.autoLandscape&&screen.orientation?.lock)try{await screen.orientation.lock('landscape')}catch{toast('Orientation lock unavailable; rotate your device manually.')}}catch{toast('Fullscreen unavailable. Continuing in windowed mode.')}}
$$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
let ersLatched=false,aeroLatched=false;
function clearInputs(){ersLatched=false;aeroLatched=false;keys.clear();touchInputs={};filtered={steer:0,throttle:0,brake:0,ers:false,aero:false};raw={...filtered};$$('.pressed').forEach(e=>e.classList.remove('pressed'))}
function action(a){if(a==='settings'){showSettings();return}if(a==='fullscreen'){fullscreen();return}if(a==='pause'){if(state==='race'||state==='countdown')pause();else if(state==='paused')resume();return}if(a==='camera'){cameraMode=(cameraMode+1)%4;toast(['Chase camera','Cockpit camera','High chase camera','Nose camera'][cameraMode]);return}if(state!=='race')return;if(a==='transmission'){settings.transmission=settings.transmission==='auto'?'manual':'auto';saveSettings();toast('Transmission: '+settings.transmission.toUpperCase());return}if(a==='autoBrake'){settings.autoBrake=!settings.autoBrake;saveSettings();toast('Corner brake assist '+(settings.autoBrake?'ON':'OFF'));return}if(a==='aero'){aeroLatched=!aeroLatched;return}if(a==='ers'){ersLatched=!ersLatched;return}if(a==='up'&&car.direction===1)car.gear=clamp(car.gear+1,1,8);if(a==='down'&&car.direction===1)car.gear=clamp(car.gear-1,1,8);if(a==='map')$('#minimap').classList.toggle('hidden');if(a==='hud')document.body.classList.toggle('immersive');if(a==='reset'){resetPose();car.invalid=true;clearInputs();toast('Returned to track · lap invalidated')}if(a==='pit'){if(car.s<120&&car.v<2){car.pitRemaining=12;toast('Service started · 12 seconds. Rivals continue racing.')}else toast('Stop within 120 m after the start line for pit service.')}}
let mode='race',wet=false,maxLaps=3;
$('#start').onclick=()=>{showModal('READY FOR LIGHTS OUT','SESSION BRIEFING',`<div class="info">${tracks[trackIndex].name} · ${$('#mode').selectedOptions[0].textContent}<br>${$('#weather').selectedOptions[0].textContent} · AL-02 · ${settings.transmission.toUpperCase()}<br><br>CONTROL METHOD: <b>${$('#device-name').textContent}</b><br>Stay inside the white lines. Off-track laps will not count as personal bests.<br>Tap E / ERS to toggle boost. To reverse: stop, release brake, press brake again. Gas brakes reverse motion before driving forward.<br>Active aero reduces drag. Brake before the corner.</div><div class="modal-actions"><button class="secondary" id="brief-controls">CHANGE CONTROLS</button><button class="primary" id="brief-start">START SESSION →</button></div>`);$('#brief-controls').onclick=()=>showSettings();$('#brief-start').onclick=startRace;};
function startRace(){closeModal();state='countdown';document.body.classList.add('racing');$('#race-ui').classList.remove('hidden');car=createCar({fuel:settings.startFuel,compound:settings.compound,pressure:settings.pressure});let startPose=trackAt(0);car.wx=startPose.p.x;car.wz=startPose.p.z;car.heading=Math.atan2(startPose.t.x,startPose.t.z);resetBots();telemetry=[];raceTime=0;timing=new TimingGaps();[...bots,{name:'YOU',total:0}].forEach(b=>timing.update(b.name,b.total,0));countdown=3.5;accumulator=0;mode=$('#mode').value;wet=$('#weather').value==='wet';maxLaps=mode==='practice'?Infinity:mode==='sprint'?1:3;scene.background.set(wet?'#829594':'#a2b7bd');scene.fog.color.copy(scene.background);sun.intensity=wet?1.1:3;$('#condition-label').textContent=settings.compound.toUpperCase()+' / '+(wet?'WET':'DRY');$('#session-label').textContent=tracks[trackIndex].name+' / '+mode.toUpperCase();opponents.forEach(o=>o.visible=mode==='race'||mode==='sprint');$('#tower').classList.toggle('hidden',mode==='practice'||mode==='time');$('#race-message').textContent='3';lastSectors=[];clearInputs();renderTouch();resize();initAudio();if(settings.device==='tilt')enableTilt();if(settings.device==='gamepad'&&!getPad())toast('No active controller. Keyboard and touch remain available.');}
function pause(){if(state!=='race'&&state!=='countdown')return;pausedFrom=state;state='paused';clearInputs();showModal('TAKE A BREATHER.','SESSION PAUSED',`<p class="info">${tracks[trackIndex].name} · Lap ${car.lap}<br>Your session is safely paused.</p><div class="modal-actions"><button id="resume" class="primary">BACK ON TRACK →</button><button id="pause-settings" class="secondary">SETTINGS</button></div><div class="modal-actions"><button id="pause-full" class="secondary">FULLSCREEN</button><button id="restart" class="secondary">RESTART</button><button id="exit" class="secondary">EXIT TO PADDOCK</button></div>`);$('#resume').onclick=resume;$('#pause-settings').onclick=()=>showSettings();$('#pause-full').onclick=fullscreen;$('#restart').onclick=startRace;$('#exit').onclick=exitRace;}
function resume(){if(editing)finishEdit(false);closeModal();state=pausedFrom;clearInputs();accumulator=0;lastFrame=performance.now();}
function exitRace(){if(editing)finishEdit(false);state='menu';closeModal();document.body.classList.remove('racing');$('#race-ui').classList.add('hidden');clearInputs();scene.background.set('#a2b7bd');scene.fog.color.copy(scene.background);opponents.forEach(o=>o.visible=true);resize();}
function finishRace(){state='finished';clearInputs();let pos=1+bots.filter(b=>b.total>car.total).length;showModal('THE LINE IS ONLY THE BEGINNING.','SESSION COMPLETE',`<div class="garage-grid" style="grid-template-columns:1fr 1fr;padding:20px"><div><small>${mode==='time'?'TIME ATTACK':'FINISH'}</small><h2>${mode==='time'?'COMPLETE':'P'+pos}</h2></div><div><small>BEST CLEAN LAP</small><h2>${formatTime(car.best)}</h2></div></div><p class="info">${maxLaps} laps · ${formatTime(raceTime)} total<br>${Number.isFinite(car.best)?'Your clean laps are saved locally.':'No clean laps recorded. Keep all four wheels on the circuit.'}</p><div class="modal-actions"><button id="again" class="primary">RACE AGAIN →</button><button id="paddock" class="secondary">PADDOCK</button></div>`);$('#again').onclick=startRace;$('#paddock').onclick=exitRace;}
function showModal(title,kicker,content){$('#modal-title').textContent=title;$('#modal-kicker').textContent=kicker;$('#modal-content').innerHTML=content;$('#modal').classList.remove('hidden');clearInputs();}
function closeModal(){$('#modal').classList.add('hidden');rebind=null;}
$('#close-modal').onclick=()=>{if(editing){finishEdit(false);return}if(state==='paused')resume();else if(state==='finished')exitRace();else closeModal()};
window.addEventListener('blur',()=>{clearInputs();if(state==='race'||state==='countdown')pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearInputs();if(state==='race'||state==='countdown')pause();if(audioCtx?.state==='running')audioCtx.suspend()}else{lastFrame=performance.now();accumulator=0;if(audioCtx?.state==='suspended'&&settings.sound)audioCtx.resume().catch(()=>{})}});
window.addEventListener('keydown',e=>{if(rebind){e.preventDefault();if(e.code==='Escape'){rebind=null;showSettings('keys');return}let target=rebind;rebind=null;let conflict=Object.keys(bindings).find(k=>k!==target&&bindings[k].includes(e.code));if(conflict){showModal('KEY ALREADY ASSIGNED','BINDING CONFLICT',`<p class="info">Used by: ${labels[conflict]}. How should this binding be handled?</p><div class="modal-actions"><button class="secondary" id="replace-key">REPLACE</button><button class="secondary" id="duplicate-key">ALLOW DUPLICATE</button><button class="secondary" id="cancel-key">CANCEL</button></div>`);$('#replace-key').onclick=()=>{for(let k in bindings)bindings[k]=bindings[k].filter(c=>c!==e.code);bindKey(target,e.code)};$('#duplicate-key').onclick=()=>bindKey(target,e.code);$('#cancel-key').onclick=()=>showSettings('keys');}else bindKey(target,e.code);return;}
 if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName))return;
 let acts=Object.keys(bindings).filter(k=>bindings[k].includes(e.code));if((state==='race'||state==='countdown'||state==='paused')&&acts.length)e.preventDefault();if(e.repeat)return;keys.add(e.code);lastDevice='keyboard';if(e.code==='Escape'&&!$('#modal').classList.contains('hidden')){$('#close-modal').click();return}for(let a of acts)if(!['throttle','brake','left','right','look'].includes(a))action(a);});
window.addEventListener('keyup',e=>keys.delete(e.code));
function bindKey(action,key){bindings[action]=[...new Set([...bindings[action],key])].slice(-3);store.set('bindings',bindings);showSettings('keys');toast('Binding saved')}
function getPad(){try{return [...navigator.getGamepads()].find(g=>g&&g.connected)}catch{return null}}
window.addEventListener('gamepadconnected',()=>{padEnabled=true;toast('Controller detected · analogue controls ready')});window.addEventListener('gamepaddisconnected',()=>{clearInputs();toast('Controller disconnected · keyboard / touch available');if(state==='race')pause()});
let padLastButtons={},padMap=store.get('padMap',{steer:0,throttle:7,brake:6,ers:0,aero:1,invert:false});if(!padMap||typeof padMap!=='object')padMap={steer:0,throttle:7,brake:6,ers:0,aero:1,invert:false};
function deadzone(v,d){return Math.abs(v)<=d?0:Math.sign(v)*(Math.abs(v)-d)/(1-d)}
function readInput(){const held=a=>bindings[a]?.some(k=>keys.has(k))||Boolean(touchInputs[a]);let r={steer:Number(held('right'))-Number(held('left')),throttle:held('throttle')?1:0,brake:held('brake')?1:0,ers:ersLatched,aero:aeroLatched};if(touchInputs.steer!==undefined&&Math.abs(touchInputs.steer)>.001)r.steer=touchInputs.steer;let pad=getPad();if(pad&&padEnabled){let ps=deadzone(pad.axes[padMap.steer]||0,settings.deadzone)*(padMap.invert?-1:1);if(Math.abs(ps)>Math.abs(r.steer)){r.steer=ps;lastDevice='gamepad'}r.throttle=Math.max(r.throttle,pad.buttons[padMap.throttle]?.value||0);r.brake=Math.max(r.brake,pad.buttons[padMap.brake]?.value||0);for(let [index,a]of[[padMap.aero,'aero'],[padMap.ers,'ers'],[9,'pause'],[3,'camera'],[5,'up'],[4,'down']]){let pressed=pad.buttons[index]?.pressed;if(pressed&&!padLastButtons[index])action(a);padLastButtons[index]=pressed;}}
 if(settings.device==='tilt'&&tilt.live){if(performance.now()-tilt.last>1200){tilt.live=false;toast('Tilt signal lost · use touch steering');}else{let v=deadzone(clamp((tilt.value-tilt.neutral)/30,-1,1),settings.tiltDeadzone/30)*settings.tiltSensitivity*(settings.tiltInvert?-1:1);r.steer=clamp(v,-1,1);lastDevice='tilt'}}r.aero=aeroLatched;r.ers=ersLatched;r.steer=clamp(-r.steer*settings.sensitivity,-1,1);raw=r;return r;}
async function enableTilt(){try{if(!window.DeviceOrientationEvent)throw Error();if(typeof DeviceOrientationEvent.requestPermission==='function'){let permission=await DeviceOrientationEvent.requestPermission();if(permission!=='granted')throw Error();}window.addEventListener('deviceorientation',onOrientation);toast('Hold device centered. Waiting for motion data…');setTimeout(()=>{if(!tilt.live)toast('Motion control unavailable · touch steering remains active.')},1800)}catch{toast('Motion control unavailable · use touch steering.')}}
function onOrientation(e){let angle=screen.orientation?.angle??window.orientation??0;let value=Math.abs(angle)===90?e.beta:e.gamma;if(!Number.isFinite(value))return;tilt.value=value;if(!tilt.seen){tilt.neutral=value;tilt.seen=1;}tilt.live=true;tilt.last=performance.now();}
const defaultLayout=()=>({left:{x:.09,y:.77,size:1,opacity:.7,hidden:false},right:{x:.23,y:.77,size:1,opacity:.7,hidden:false},throttle:{x:.9,y:.73,size:1.15,opacity:.75,hidden:false},brake:{x:.75,y:.81,size:1,opacity:.75,hidden:false},ers:{x:.61,y:.85,size:.65,opacity:.65,hidden:false},aero:{x:.76,y:.55,size:.65,opacity:.65,hidden:false},camera:{x:.53,y:.18,size:.6,opacity:.6,hidden:true},up:{x:.9,y:.3,size:.6,opacity:.6,hidden:true},down:{x:.78,y:.3,size:.6,opacity:.6,hidden:true},look:{x:.63,y:.2,size:.6,opacity:.6,hidden:true},pause:{x:.46,y:.18,size:.6,opacity:.6,hidden:true},reset:{x:.35,y:.18,size:.6,opacity:.6,hidden:true},pit:{x:.35,y:.3,size:.6,opacity:.6,hidden:true},map:{x:.46,y:.3,size:.6,opacity:.6,hidden:true},hud:{x:.56,y:.3,size:.6,opacity:.6,hidden:true},transmission:{x:.45,y:.4,size:.65,opacity:.7,hidden:true},autoBrake:{x:.55,y:.4,size:.65,opacity:.7,hidden:true}});
function layoutKey(){return 'layout.'+settings.profile+'.'+(innerWidth>innerHeight?'landscape':'portrait')}
let layout=defaultLayout(),currentLayoutKey='';function loadLayout(){currentLayoutKey=layoutKey();let saved=store.get(currentLayoutKey,null);layout=saved&&validateLayout(saved)?{...defaultLayout(),...saved}:defaultLayout();}loadLayout();
function renderTouch(){if(currentLayoutKey!==layoutKey()&&!editing)loadLayout();let root=$('#touch-layer');root.replaceChildren();if(!editing&&!['touch','tilt'].includes(settings.device)&&!touchCap)return;for(let [a,c]of Object.entries(layout)){if(c.hidden)continue;if(settings.steering!=='buttons'&&a==='right')continue;let b=document.createElement('button');b.className='touch-button'+(a==='left'&&settings.steering!=='buttons'?' wheel':'');b.textContent=({left:settings.steering==='buttons'?'◀':settings.steering==='wheel'?'◀ WHEEL ▶':'◀ SLIDER ▶',right:'▶',throttle:'GAS',brake:'BRAKE',ers:'ERS',aero:'AERO',up:'GEAR +',down:'GEAR −',camera:'CAM',look:'REAR',pause:'⏸',reset:'RESET',pit:'PIT',map:'MAP',hud:'HUD',transmission:'GEAR MODE',autoBrake:'AUTO BRAKE'})[a];if(a==='pause')b.innerHTML='<svg width="14" height="16" viewBox="0 0 14 16" aria-hidden="true"><rect x="1" width="4" height="16" fill="currentColor"/><rect x="9" width="4" height="16" fill="currentColor"/></svg>';b.setAttribute('aria-label',labels[a]);b.dataset.control=a;b.style.left=`${c.x*100}%`;b.style.top=`${c.y*100}%`;b.style.opacity=editing?1:c.opacity;b.style.width=`${(a==='left'&&settings.steering!=='buttons'?140:68)*c.size}px`;b.style.height=`${68*c.size}px`;if(editing&&a===selectedControl)b.classList.add('selected');
 let dragging=false,pointer=null,startX=0;const analog=e=>{let r=b.getBoundingClientRect();touchInputs.steer=clamp((e.clientX-(r.left+r.width/2))/(r.width/2),-1,1)};
 b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);pointer=e.pointerId;lastDevice='touch';if(editing){dragging=true;selectedControl=a;syncEditor();$$('.touch-button').forEach(x=>x.classList.toggle('selected',x===b));}else{b.classList.add('pressed');touchInputs[a]=true;if(a==='left'&&settings.steering!=='buttons'){delete touchInputs.left;analog(e);}if(!['throttle','brake','left','right','look'].includes(a))action(a);}};
 b.onpointermove=e=>{if(e.pointerId!==pointer)return;if(dragging){let r=root.getBoundingClientRect(),halfX=b.offsetWidth/2/r.width,halfY=b.offsetHeight/2/r.height;c.x=clamp((e.clientX-r.left)/r.width,halfX,1-halfX);c.y=clamp((e.clientY-r.top)/r.height,halfY,1-halfY);if($('#snap')?.checked){c.x=clamp(Math.round(c.x*20)/20,halfX,1-halfX);c.y=clamp(Math.round(c.y*20)/20,halfY,1-halfY)}b.style.left=c.x*100+'%';b.style.top=c.y*100+'%';}else if(a==='left'&&settings.steering!=='buttons')analog(e);};
 const end=()=>{dragging=false;pointer=null;delete touchInputs[a];if(a==='left')delete touchInputs.steer;b.classList.remove('pressed')};b.onpointerup=end;b.onpointercancel=end;b.onlostpointercapture=end;root.append(b);}
 // Clamp visible hit targets after every viewport change, including notches and fullscreen.
 touchInputs={};let r=root.getBoundingClientRect();if(r.width&&r.height)for(let b of root.children){let a=b.dataset.control,c=layout[a],hx=Math.min(.48,b.offsetWidth/(2*r.width)),hy=Math.min(.48,b.offsetHeight/(2*r.height));b.style.left=clamp(c.x,hx,1-hx)*100+'%';b.style.top=clamp(c.y,hy,1-hy)*100+'%';}}
function startEdit(){if(state==='race'||state==='countdown'){pausedFrom=state;state='paused'}editSnapshot=structuredClone(layout);editing=true;document.body.classList.add('racing','editing');$('#race-ui').classList.remove('hidden');showModal('MAKE ROOM FOR YOUR RACING LINE.','DRAG CONTROLS TO POSITION',`<div class="setting"><label>Selected control</label><select id="edit-select">${Object.keys(labels).map(a=>`<option value="${a}">${labels[a]}</option>`).join('')}</select></div><div class="setting"><label>Size · 50–200%</label><input id="edit-size" type="range" min="0.5" max="2" step="0.05"></div><div class="setting"><label>Race opacity</label><input id="edit-opacity" type="range" min="0.1" max="1" step="0.05"></div><div class="setting"><label>Visible</label><input type="checkbox" id="edit-visible"><label>Snap to grid <input id="snap" type="checkbox"></label></div><div class="modal-actions"><button class="primary" id="save-layout">SAVE</button><button class="secondary" id="cancel-layout">CANCEL</button><button class="secondary" id="reset-layout">RESET</button></div>`);$('#edit-select').value=selectedControl;$('#edit-select').onchange=e=>{selectedControl=e.target.value;syncEditor();renderTouch()};$('#edit-size').oninput=e=>{layout[selectedControl].size=Number(e.target.value);renderTouch()};$('#edit-opacity').oninput=e=>{layout[selectedControl].opacity=Number(e.target.value);renderTouch()};$('#edit-visible').onchange=e=>{if(['left','right','throttle','brake'].includes(selectedControl)&&!e.target.checked){e.target.checked=true;toast('Essential controls remain visible for safe driving.');return}layout[selectedControl].hidden=!e.target.checked;renderTouch()};$('#save-layout').onclick=()=>finishEdit(true);$('#cancel-layout').onclick=()=>finishEdit(false);$('#reset-layout').onclick=()=>{layout=defaultLayout();syncEditor();renderTouch()};syncEditor();renderTouch();resize();}
function syncEditor(){if(!$('#edit-select'))return;$('#edit-select').value=selectedControl;$('#edit-size').value=layout[selectedControl].size;$('#edit-opacity').value=layout[selectedControl].opacity;$('#edit-visible').checked=!layout[selectedControl].hidden;}
function finishEdit(save){if(save){store.set(layoutKey(),layout);toast('Layout saved for '+(innerWidth>innerHeight?'landscape':'portrait'))}else layout=editSnapshot;editing=false;document.body.classList.remove('editing');if(state==='menu'){document.body.classList.remove('racing');$('#race-ui').classList.add('hidden')}closeModal();renderTouch();resize();showSettings('touch');}
function option(v,label,cur){return `<option value="${v}"${String(cur)===String(v)?' selected':''}>${label}</option>`}function selectSetting(id,label,options,current,note=''){return `<div class="setting"><label for="${id}">${label}${note?'<small>'+note+'</small>':''}</label><select id="${id}">${options.map(([v,l])=>option(v,l,current)).join('')}</select></div>`}function checkSetting(id,label,checked,note=''){return `<div class="setting"><label for="${id}">${label}${note?'<small>'+note+'</small>':''}</label><input type="checkbox" id="${id}" ${checked?'checked':''}></div>`}function rangeSetting(id,label,value,min,max,step){return `<div class="setting"><label for="${id}">${label}</label><input id="${id}" type="range" min="${min}" max="${max}" step="${step}" value="${value}"></div>`}
function showSettings(tab='drive'){if(state==='race'||state==='countdown'){pausedFrom=state;state='paused'}let nav=`<div class="tabs">${[['drive','DRIVING'],['keys','KEYBOARD'],['touch','TOUCH / TILT'],['pad','GAMEPAD'],['display','DISPLAY']].map(([t,n])=>`<button data-tab="${t}" class="${tab===t?'active':''}">${n}</button>`).join('')}</div>`,html='';
 if(tab==='drive')html=checkSetting('set-autoBrake','Automatic corner braking · V',settings.autoBrake,'Conservative recommended speeds, not a guaranteed fastest lap.')+rangeSetting('set-engineBraking','Engine braking / coast recovery',settings.engineBraking,0,1,.1)+selectSetting('set-assist','Driving assists',[['casual','Assisted · TC + ABS, no damage'],['simulation','Simulation · TC + ABS, damage'],['hardcore','Hardcore · no TC / ABS']],settings.assist)+selectSetting('set-ersMode','ERS strategy',[['manual','Manual · toggle E'],['off','Off'],['harvest','Harvest'],['balanced','Balanced'],['attack','Attack']],settings.ersMode)+selectSetting('set-device','How do you want to drive?',[['keyboard','Keyboard'],['gamepad','Gamepad'],['touch','Touch'],['tilt','Tilt + touch']],settings.device)+selectSetting('set-transmission','Transmission',[['auto','Automatic'],['manual','Manual']],settings.transmission)+rangeSetting('set-sensitivity','Steering sensitivity',settings.sensitivity,.4,1.5,.05)+checkSetting('set-sound','Engine audio',settings.sound)+rangeSetting('set-volume','Audio volume',settings.volume,0,.5,.01)+`<div class="input-bars"><div>STEERING<meter id="lab-steer" min="-1" max="1" value="0"></meter></div><div>THROTTLE<meter id="lab-throttle" value="0"></meter></div><div>BRAKE<meter id="lab-brake" value="0"></meter></div></div><p class="info">Control test lab · press a key or move your controller. Inputs share one vehicle model. Brake and throttle work simultaneously with touch steering.</p><pre class="diagnostic" id="diagnostic"></pre>`;
 if(tab==='keys')html=`<p class="info">Click a binding, then press a key to add it (up to three per action). Escape cancels. Conflicts are checked before saving.</p>${Object.entries(labels).map(([a,l])=>`<div class="setting"><label>${l}</label><button class="binding" data-bind="${a}"></button></div>`).join('')}<div class="modal-actions"><button class="secondary" id="keys-default">RESET DEFAULTS</button><button class="secondary" id="keys-left">LEFT-HANDED · IJKL</button></div>`;
 if(tab==='touch')html=selectSetting('set-profile','Saved profile',['Default','Two-thumb','Left-hand dominant','Right-hand dominant','Sim','Custom 1','Custom 2'].map(x=>[x,x]),settings.profile)+selectSetting('set-steering','Touch steering',[['buttons','Two buttons'],['wheel','Virtual wheel (drag)'],['slider','Steering slider']],settings.steering)+`<div class="setting"><label>Touch layout<small>Drag, resize, hide optional controls. Separate orientation saves.</small></label><button id="edit-layout">EDIT LAYOUT</button></div><div class="setting"><label>Motion input<small id="tilt-status">${tilt.live?'Live sensor data received':'Not verified · permission / sensor data required'}</small></label><button id="tilt-enable">ENABLE TILT</button></div><div class="setting"><label>Neutral orientation</label><button id="calibrate">CENTER & CALIBRATE</button></div>`+rangeSetting('set-tiltSensitivity','Tilt sensitivity',settings.tiltSensitivity,.3,2,.1)+rangeSetting('set-tiltDeadzone','Tilt deadzone (degrees)',settings.tiltDeadzone,0,12,1)+checkSetting('set-tiltInvert','Invert tilt steering',settings.tiltInvert)+`<div class="modal-actions"><button id="export-layout" class="secondary">EXPORT JSON</button><button id="import-layout" class="secondary">IMPORT JSON</button><input id="layout-file" type="file" accept="application/json" hidden></div>`;
 if(tab==='pad')html=`<p class="info">Standard controller: left stick steering, RT throttle, LT brake, A ERS, B aero, Y camera, bumpers shift, Start pause. Press a controller button to expose it to the browser.</p>`+selectSetting('pad-steer','Steering axis',Array.from({length:8},(_,i)=>[i,'Axis '+i]),padMap.steer)+selectSetting('pad-throttle','Throttle button / trigger',Array.from({length:18},(_,i)=>[i,'Button '+i]),padMap.throttle)+selectSetting('pad-brake','Brake button / trigger',Array.from({length:18},(_,i)=>[i,'Button '+i]),padMap.brake)+checkSetting('pad-invert','Invert steering axis',padMap.invert)+rangeSetting('set-deadzone','Stick deadzone',settings.deadzone,0,.4,.01)+`<pre class="diagnostic" id="pad-diagnostic">No active controller</pre>`;
 if(tab==='display')html=selectSetting('set-quality','Rendering quality',[['low','Low · 70% resolution'],['medium','Medium · native resolution'],['high','High · shadows + 1.35×'],['ultra','Ultra · shadows + 1.75×']],settings.quality)+selectSetting('set-display','Display mode',[['windowed','Windowed'],['fullscreen','Fullscreen'],['immersive','Immersive · reduced HUD'],['cinematic','Cinematic · screenshots']],settings.display)+checkSetting('set-autoLandscape','Auto landscape on fullscreen',settings.autoLandscape,'Where browser orientation locking is permitted.')+checkSetting('set-highContrast','High contrast interface',settings.highContrast)+checkSetting('set-largeUI','Larger settings text',settings.largeUI)+`<div class="setting"><label>Fullscreen<small>Requires a user gesture. Availability varies by browser.</small></label><button id="display-full">TOGGLE FULLSCREEN</button></div><p class="info">Camera shake and flashing effects are disabled by design. The simulation automatically pauses when focus is lost. All race messages are shown as text.<br><br>WebGL: active · Touch: ${touchCap?'detected':'not detected'}<br>Gamepad: ${getPad()?'connected':'not verified'} · Motion: ${tilt.live?'receiving data':'not verified'}<br>Viewport: ${innerWidth} × ${innerHeight} · DPR: ${devicePixelRatio}</p>`;
 showModal('DRIVE YOUR WAY.','SETTINGS / SAVED AUTOMATICALLY',nav+html);$$('[data-tab]').forEach(b=>b.onclick=()=>showSettings(b.dataset.tab));
 for(let key of Object.keys(settings)){let el=$('#set-'+key);if(!el)continue;el.onchange=async()=>{settings[key]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;saveSettings();if(key==='profile'){loadLayout();if(!store.get(layoutKey(),null)&&key){if(settings.profile==='Left-hand dominant'){for(let c of Object.values(layout))c.x=1-c.x;}if(settings.profile==='Sim')for(let c of Object.values(layout))c.hidden=false;if(settings.profile==='Two-thumb'){layout.throttle.x=.89;layout.brake.x=.72;}store.set(layoutKey(),layout)}}if(key==='device'&&settings.device==='tilt')enableTilt();if(key==='sound'&&settings.sound)initAudio();if(key==='display'){if(['fullscreen','immersive'].includes(settings.display)&&!document.fullscreenElement)fullscreen();if(settings.display==='windowed'&&document.fullscreenElement)document.exitFullscreen().catch(()=>{});}renderTouch()};}
 if(tab==='keys'){$$('[data-bind]').forEach(b=>{b.textContent=bindings[b.dataset.bind].join(' / ')||'UNASSIGNED';b.onclick=()=>{rebind=b.dataset.bind;b.textContent='PRESS NEW KEY · ESC TO CANCEL'}});$('#keys-default').onclick=()=>{bindings=structuredClone(defaultBindings);store.set('bindings',bindings);showSettings('keys')};$('#keys-left').onclick=()=>{bindings=structuredClone(defaultBindings);Object.assign(bindings,{throttle:['KeyI'],brake:['KeyK'],left:['KeyJ'],right:['KeyL']});store.set('bindings',bindings);showSettings('keys')}}
 if(tab==='touch'){$('#edit-layout').onclick=startEdit;$('#tilt-enable').onclick=()=>{settings.device='tilt';saveSettings();enableTilt()};$('#calibrate').onclick=()=>{if(!tilt.live){toast('No motion signal. Enable tilt on a supported device first.');return}tilt.neutral=tilt.value;toast('Tilt center calibrated')};$('#export-layout').onclick=()=>downloadJSON({version:1,layout},'apex-touch-layout.json');$('#import-layout').onclick=()=>$('#layout-file').click();$('#layout-file').onchange=async e=>{try{let f=e.target.files[0];if(!f||f.size>100000)throw Error();let parsed=JSON.parse(await f.text());if(parsed.version!==1||!validateLayout(parsed.layout)||Object.keys(parsed.layout).some(k=>!labels[k]))throw Error();for(let k of ['left','right','throttle','brake'])if(parsed.layout[k]?.hidden)throw Error();layout={...defaultLayout(),...parsed.layout};store.set(layoutKey(),layout);toast('Validated layout imported');}catch{toast('Invalid layout. Your existing controls were preserved.')}};}
 if(tab==='pad'){for(let k of ['steer','throttle','brake','invert'])$('#pad-'+k).onchange=e=>{padMap[k]=k==='invert'?e.target.checked:Number(e.target.value);store.set('padMap',padMap)}}if(tab==='display')$('#display-full').onclick=fullscreen;
}
function downloadJSON(data,name){let url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
let audioCtx,osc,gain;
function initAudio(){if(!settings.sound)return;try{if(!audioCtx){audioCtx=new(window.AudioContext||window.webkitAudioContext)();osc=audioCtx.createOscillator();osc.type='sawtooth';gain=audioCtx.createGain();let filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;osc.connect(filter);filter.connect(gain);gain.connect(audioCtx.destination);gain.gain.value=0;osc.start()}audioCtx.resume().catch(()=>{})}catch{toast('Audio unavailable; gameplay is unaffected.')}}
function updateAudio(){if(!gain)return;let active=state==='race'&&settings.sound&&!document.hidden;gain.gain.setTargetAtTime(active?settings.volume*.08*(.35+car.throttle*.65):0,audioCtx.currentTime,.1);osc.frequency.setTargetAtTime(40+car.rpm/80,audioCtx.currentTime,.05)}
$('#rpm-leds').innerHTML='<i></i>'.repeat(12);
let hudTick=0;
function updateHUD(dt){hudTick+=dt;if(hudTick<.07)return;hudTick=0;$('#speed').textContent=Math.round(car.v*3.6);$('#gear').textContent=car.direction===-1?'R':car.gear;$('#lap').textContent=Math.min(car.lap,maxLaps)+' / '+(maxLaps===Infinity?'∞':maxLaps);$('#lap-time').textContent=formatTime(car.lapTime);$('#best-time').textContent=car.invalid?'LAP INVALID · TRACK LIMITS':'BEST '+formatTime(car.best);$('#ers-value').textContent=Math.round(car.ers)+'%';$('#ers-bar').style.width=car.ers+'%';$('#fuel').textContent=car.fuel.toFixed(1)+' kg';$('#power-state').textContent=car.deployKW>0?'BOOST +'+Math.round(car.deployKW)+' kW':ersLatched?'ERS ON / READY':'ERS OFF / '+settings.ersMode.toUpperCase();$('#mechanical-state').textContent=settings.transmission.toUpperCase()+' [G] · REGEN '+Math.round(car.regenKW||0)+' kW';$('#service-state').textContent=car.pitRemaining>0?'PIT SERVICE '+car.pitRemaining.toFixed(1)+'s':brakeGuide.active?'AUTO BRAKE → '+Math.round(brakeGuide.target*3.6)+' KM/H':settings.autoBrake?'BRAKE ASSIST ON [V] · TARGET '+Math.round(brakeGuide.target*3.6)+' KM/H':'BRAKE ASSIST OFF [V]';$('#tyres').textContent=Math.round(car.tyres)+'% · '+Math.round(car.wheels.reduce((a,w)=>a+w.temp,0)/4)+'°C';$('#damage').textContent=Math.round(car.damage)+'%';$('#aero-state').textContent=car.aeroOpen?'OPEN':aeroLatched?'ON / WAITING':'OFF';$('#throttle-meter').style.transform=`scaleX(${car.throttle})`;$('#brake-meter').style.transform=`scaleX(${car.brake})`;$$('[data-control="aero"]').forEach(b=>{b.textContent=aeroLatched?'AERO ON':'AERO OFF';b.setAttribute('aria-pressed',String(aeroLatched))});$$('[data-control="ers"]').forEach(b=>{b.setAttribute('aria-pressed',String(ersLatched));b.textContent=ersLatched?'ERS ON':'ERS OFF'});$$('#rpm-leds i').forEach((el,i)=>el.classList.toggle('on',i<(car.rpm-5000)/7500*12));let order=[...bots.map(b=>({...b,you:false})),{name:'YOU',total:car.total,you:true}].sort((a,b)=>b.total-a.total);const leaderMode=Math.floor(raceTime/3)%2===0;$('#tower .panel-heading').textContent=leaderMode?'GAP TO LEADER':'INTERVAL';$('#positions').innerHTML=order.map((b,i)=>`<div class="position-row ${b.you?'you':''}"><b>${i+1}</b><span>${b.name}</span><small>${i===0?'LEADER':timing.gap(leaderMode?order[0]:order[i-1],b,length)}</small></div>`).join('');drawMap();}
function drawMap(){let ctx=$('#minimap').getContext('2d');ctx.clearRect(0,0,220,160);let minX=Infinity,minZ=Infinity,maxX=-Infinity,maxZ=-Infinity;for(let a of samples){minX=Math.min(minX,a.p.x);maxX=Math.max(maxX,a.p.x);minZ=Math.min(minZ,a.p.z);maxZ=Math.max(maxZ,a.p.z)}let scale=Math.min(184/(maxX-minX),124/(maxZ-minZ));const xy=p=>[18+(p.x-minX)*scale,18+(p.z-minZ)*scale];ctx.beginPath();samples.forEach((a,i)=>{let p=xy(a.p);i?ctx.lineTo(...p):ctx.moveTo(...p)});ctx.strokeStyle='#111a12b0';ctx.lineWidth=8;ctx.stroke();ctx.strokeStyle='#c4cdb7';ctx.lineWidth=2;ctx.stroke();for(let z of tracks[trackIndex].aeroZones){ctx.beginPath();for(let i=0;i<=30;i++){let p=xy(trackAt((z.start+(z.end-z.start)*i/30)*length).p);i?ctx.lineTo(...p):ctx.moveTo(...p)}ctx.strokeStyle='#d5ff43';ctx.lineWidth=4;ctx.stroke();}if(mode==='race'||mode==='sprint')for(let b of bots){let p=xy(trackAt(b.s).p);ctx.beginPath();ctx.arc(...p,2.6,0,Math.PI*2);ctx.fillStyle='#f6f2e6';ctx.fill()}let p=xy(trackAt(car.s).p);ctx.beginPath();ctx.arc(...p,4.5,0,Math.PI*2);ctx.fillStyle='#d5ff43';ctx.fill();}
let menuClock=0,camInitialized=false;
function renderWorld(dt){if(state==='menu'&&!editing){menuClock+=dt;let a=place(carModel,65);let focus=carModel.position.clone().add(new THREE.Vector3(0,.5,0));let offset=a.n.clone().multiplyScalar(7.9).addScaledVector(a.t,7.5);offset.y=4.1;camera.position.copy(focus).add(offset);camera.lookAt(focus.clone().addScaledVector(a.n,-3.5).addScaledVector(a.t,2.0));camera.fov=innerWidth<600?48:39;camera.updateProjectionMatrix();for(let i=0;i<bots.length;i++)place(opponents[i],300+i*65,(i%2?1:-1)*3);camInitialized=false;
 }else{let a=trackAt(car.s);carModel.position.set(car.wx,0,car.wz);carModel.rotation.y=car.heading+Math.PI;animateModel(carModel,car,dt);a.t.set(Math.sin(car.heading),0,Math.cos(car.heading));a.p.copy(carModel.position);a.n.set(Math.cos(car.heading),0,-Math.sin(car.heading));let back=bindings.look.some(k=>keys.has(k))||touchInputs.look;let target=a.p.clone();let camPos=target.clone(),look=target.clone();if((cameraMode===1||cameraMode===3)&&!back){camPos.addScaledVector(a.t,cameraMode===3?2.0:.35);camPos.y=cameraMode===3?.65:1.16;look.addScaledVector(a.t,45);look.y=1.6;}else{camPos.addScaledVector(a.t,back?11:cameraMode===2?-19:-11);camPos.y=cameraMode===2?10:5;look.addScaledVector(a.t,back?-20:18);look.y=1;}
 if(!camInitialized){camera.position.copy(camPos);camInitialized=true}else camera.position.lerp(camPos,1-Math.exp(-dt*8));camera.lookAt(look);camera.fov=cameraMode===1?72:58;camera.updateProjectionMatrix();for(let i=0;i<bots.length;i++)place(opponents[i],bots[i].s,bots[i].x);}
 sun.position.copy(carModel.position).add(new THREE.Vector3(-40,90,60));sun.target.position.copy(carModel.position);renderer.render(scene,camera);}
function simulation(dt){let input=readInput();filtered={...input,steer:car.steer,throttle:car.throttle,brake:car.brake};if(state==='countdown'){countdown-=dt;$('#race-message').textContent=countdown>0?Math.ceil(countdown):'GO';if(countdown<=0){state='race';setTimeout(()=>{if(state==='race')$('#race-message').textContent=''},900)}return}if(state!=='race')return;raceTime+=dt;const gripFactor=(wet?(car.compound==='wet'?.75:car.compound==='inter'?.65:.48):1)*clamp(car.tyres/100,.6,1)*clamp(1-car.damage*.004,.6,1);brakeGuide=cornerAssist(raceProfile,car,input,settings.autoBrake,gripFactor);input=brakeGuide.input;let previousS=car.s;let zone=tracks[trackIndex].aeroZones.some(z=>car.s/length>=z.start&&car.s/length<=z.end);stepCar(car,input,dt,{width:roadWidth,length,wet,setup:settings.setup,manual:settings.transmission==='manual',aeroZone:zone,assist:settings.assist,brakeBias:settings.brakeBias,rideHeight:settings.rideHeight,ersMode:ersLatched?settings.ersMode:'off',startFuel:settings.startFuel,engineBraking:settings.engineBraking});let lap=projectCar(previousS);
 if(mode==='race'||mode==='sprint')for(let [i,b]of bots.entries()){let base=$('#difficulty').value==='easy'?62:$('#difficulty').value==='hard'?86:75;let turn=Math.max(...[25,70,140].map(d=>Math.abs(curvature(b.s+d))));let target=Math.min(base,Math.sqrt(13/Math.max(turn,.002)))*(wet?.72:1);let ahead=bots.find(o=>o!==b&&((o.s-b.s+length)%length)<20&&Math.abs(o.x-b.x)<2.5);b.x=approach(b.x,ahead?-Math.sign(b.x||1)*3:(i%2?2:-2),dt*1.2);b.v=approach(b.v,target,dt*7);b.s=(b.s+b.v*dt)%length;b.total+=b.v*dt;let d=(b.s-car.s+length*1.5)%length-length/2;if(Math.abs(d)<4.5&&Math.abs(b.x-car.x)<2.4){car.u=Math.min(car.u,b.v*.97);car.lateral+=(car.x>=b.x?1:-1)*dt*3;if(settings.assist!=='casual')car.parts.frontWing=clamp(car.parts.frontWing+dt*4,0,100);}}
 for(const b of [...bots,{name:'YOU',total:car.total}])timing.update(b.name,b.total,raceTime);
 telemetryClock+=dt;if(telemetryClock>.1){telemetryClock=0;telemetry.push([raceTime,car.s,car.v*3.6,car.rpm,car.gear,car.steerAngle,car.throttle,car.brake,car.ers,car.deployKW,car.aeroOpen?1:0,car.downforce,car.fuel,...car.wheels.map(w=>w.temp)]);if(telemetry.length>18000)telemetry.shift();}if(lap){if(lap.valid){let k=tracks[trackIndex].name+' / '+(wet?'WET':'DRY')+' / '+settings.assist;if(!records[k]||lap.time<records[k]){records[k]=lap.time;store.set('records.v3',records);toast('New personal best · '+formatTime(lap.time))}else toast('Clean lap · '+formatTime(lap.time));}else toast('Lap not recorded · track limits');if(car.lap>maxLaps)finishRace();}}
function frame(now){requestAnimationFrame(frame);if(document.hidden){lastFrame=now;return}let dt=Math.min((now-lastFrame)/1000,.1);lastFrame=now;fps=approach(fps,1/Math.max(dt,.001),1);if(state==='race'||state==='countdown'){accumulator+=dt;while(accumulator>=1/120){simulation(1/120);accumulator-=1/120;}}else if(!$('#modal').classList.contains('hidden'))readInput();
 if($('#lab-steer')){$('#lab-steer').value=raw.steer;$('#lab-throttle').value=raw.throttle;$('#lab-brake').value=raw.brake;$('#diagnostic').textContent=`ACTIVE INPUT  ${lastDevice.toUpperCase()}\nNORMALIZED    steer ${raw.steer.toFixed(2)} / gas ${raw.throttle.toFixed(2)} / brake ${raw.brake.toFixed(2)}\nPHYSICS       steer ${car.steer.toFixed(2)} / gas ${car.throttle.toFixed(2)}\nRENDER        ${Math.round(fps)} fps · fixed physics 120 Hz`;}if($('#pad-diagnostic')){let pad=getPad();$('#pad-diagnostic').textContent=pad?`${pad.id}\nAXES ${pad.axes.map(v=>v.toFixed(2)).join(' / ')}\nTHROTTLE ${Math.round((pad.buttons[padMap.throttle]?.value||0)*100)}%   BRAKE ${Math.round((pad.buttons[padMap.brake]?.value||0)*100)}%`:'No active controller. Press a button to connect.';}updateAudio();if(state!=='menu')updateHUD(dt);renderWorld(dt);}
requestAnimationFrame(frame);
// Read-only diagnostics are useful for reproducible browser QA.
window.apexDebug={snapshot:()=>({state,car:{...car},raw:{...raw},layout:structuredClone(layout),track:length,settings:{...settings},cameraAspect:camera.aspect,renderStats:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles},flaps:{rear:carModel.userData.rearFlap.rotation.x,front:carModel.userData.frontFlaps[0].rotation.x},zones:tracks[trackIndex].aeroZones}),start:startRace};

let telemetry=[],telemetryClock=0;
function resetPose(){let a=trackAt(car.s);car.wx=a.p.x;car.wz=a.p.z;car.heading=Math.atan2(a.t.x,a.t.z);car.u=0;car.v=0;car.lateral=0;car.yaw=0;car.x=0;car.lapProgress=0;}
function projectCar(previousS){
 const count=samples.length-1;let seed=Math.floor(previousS/length*count),best=Infinity,result=null;
 for(let j=-16;j<=16;j++){let i=(seed+j+count)%count,a=samples[i].p,b=samples[i+1].p,dx=b.x-a.x,dz=b.z-a.z,q=clamp(((car.wx-a.x)*dx+(car.wz-a.z)*dz)/(dx*dx+dz*dz),0,1),px=a.x+dx*q,pz=a.z+dz*q,d=(car.wx-px)**2+(car.wz-pz)**2;if(d<best){best=d;let l=Math.hypot(dx,dz);result={s:(i+q)/count*length,x:(car.wx-px)*dz/l-(car.wz-pz)*dx/l,nx:dz/l,nz:-dx/l,px,pz};}}
 car.s=result.s%length;car.x=result.x;let delta=car.s-previousS;if(delta>length/2)delta-=length;if(delta<-length/2)delta+=length;car.total+=delta;car.lapProgress=Math.max(0,car.lapProgress+delta);
 if(Math.abs(car.x)>roadWidth/2+1)car.invalid=true;
 if(Math.abs(car.x)>16.5){let sign=Math.sign(car.x),penetration=Math.abs(car.x)-16.5;car.wx-=result.nx*penetration*sign;car.wz-=result.nz*penetration*sign;let normalSpeed=(Math.sin(car.heading)*car.u+Math.cos(car.heading)*car.lateral)*result.nx+(Math.cos(car.heading)*car.u-Math.sin(car.heading)*car.lateral)*result.nz;
 if(normalSpeed*sign>0){let vx=Math.sin(car.heading)*car.u+Math.cos(car.heading)*car.lateral-normalSpeed*result.nx*1.15,vz=Math.cos(car.heading)*car.u-Math.sin(car.heading)*car.lateral-normalSpeed*result.nz*1.15;car.u=vx*Math.sin(car.heading)+vz*Math.cos(car.heading);car.lateral=vx*Math.cos(car.heading)-vz*Math.sin(car.heading);car.yaw*=.6;if(settings.assist!=='casual'){car.parts.frontWing=clamp(car.parts.frontWing+Math.max(0,Math.abs(normalSpeed)-2)*1.2,0,100);car.parts.suspension=clamp(car.parts.suspension+Math.max(0,Math.abs(normalSpeed)-6)*.4,0,100);car.parts.floor=clamp(car.parts.floor+Math.abs(normalSpeed)*.2,0,100);}}car.x=16.5*sign;car.invalid=true;}
 let sector=Math.floor(car.s/length*3);if(sector>car.sector){car.sectorTimes.push(car.lapTime-car.sectorTimes.reduce((a,b)=>a+b,0));car.sector=sector;}
 if(previousS>length*.85&&car.s<length*.15&&delta>0&&car.lapProgress>length*.9){let time=car.lapTime,valid=!car.invalid;car.sectorTimes.push(time-car.sectorTimes.reduce((a,b)=>a+b,0));lastSectors=[...car.sectorTimes];car.sectorTimes=[];car.sector=0;car.lap++;car.lapTime=0;car.lapProgress=0;if(valid)car.best=Math.min(car.best,time);car.invalid=false;return{lap:true,time,valid};}return null;
}
let lastSectors=[];
function refreshTrackCard(){let t=tracks[trackIndex];$('#track-name').textContent=t.name;$('#track-detail').textContent=t.reference.toUpperCase()+' REFERENCE · '+(length/1000).toFixed(2)+' KM';let xs=t.shape.map(p=>p[0]),zs=t.shape.map(p=>p[1]),minX=Math.min(...xs),minZ=Math.min(...zs),scale=Math.min(180/(Math.max(...xs)-minX),85/(Math.max(...zs)-minZ));$('.track-icon path').setAttribute('d',t.shape.map(([x,z],i)=>(i?'L':'M')+(20+(x-minX)*scale).toFixed(1)+' '+(6+(z-minZ)*scale).toFixed(1)).join(' ')+'Z');}
function showTracks(){showModal('FIVE CIRCUITS. ONE LIMIT.','GEOREFERENCED OUTLINES / ORIGINAL SCENERY',`<p class="info">Real map-derived planforms. Width, elevation, scenery and aero-zone rules are simplified—not surveyed replicas.</p><div class="track-list">${tracks.map((t,i)=>`<button class="secondary track-choice" data-track="${i}"><strong>${t.name}</strong><span>${t.reference} reference · ${(t.length/1000).toFixed(3)} km nominal</span></button>`).join('')}</div><p class="info">Circuit data © Tomislav Bacinger · MIT. Attribution in LICENSES.md. No championship affiliation.</p>`);$$('[data-track]').forEach(b=>b.onclick=()=>{trackIndex=Number(b.dataset.track);buildTrack();refreshTrackCard();closeModal();toast(tracks[trackIndex].name+' selected')})}

$('#engineering').onclick=()=>{showModal('SETUP WITH CONSEQUENCES.','RACE ENGINEERING / AL-02',selectSetting('eng-compound','Tyre compound',[['soft','Soft · peak grip'],['medium','Medium · balanced'],['hard','Hard · durability'],['inter','Intermediate · damp'],['wet','Wet · rain']],settings.compound)+rangeSetting('eng-engine','Engine braking / coast recovery',settings.engineBraking,0,1,.1)+rangeSetting('eng-fuel','Starting fuel · kg',settings.startFuel,5,100,1)+rangeSetting('eng-bias','Brake bias · front fraction',settings.brakeBias,.48,.66,.01)+rangeSetting('eng-pressure','Tyre pressure · psi',settings.pressure,18,28,.5)+rangeSetting('eng-ride','Ride height · metres',settings.rideHeight,.035,.12,.005)+`<p class="info">Engine braking controls off-throttle drag and 12–30 kW coast recovery; heavier pedal braking can recover up to 110 kW. Recovery is limited by rear grip, speed and battery headroom. Fuel changes mass. Compound, pressure and temperature alter tyre grip. Brake bias distributes wheel braking. Ride height changes floor efficiency. Aero balance is set in the garage.<br><br>Changes apply from your next session. In-race service: stop within 120 m after the start line and press P. Service takes 12 seconds while rivals continue.</p>`);for(let [id,key]of [['engine','engineBraking'],['compound','compound'],['fuel','startFuel'],['bias','brakeBias'],['pressure','pressure'],['ride','rideHeight']])$('#eng-'+id).onchange=e=>{settings[key]=id==='compound'?e.target.value:Number(e.target.value);saveSettings();};};
function showTelemetry(){if(state==='race'||state==='countdown'){pausedFrom=state;state='paused'}showModal('UNDERSTAND YOUR LAP.','TELEMETRY / LAST 30 MINUTES',`<canvas id="telemetry-chart" width="640" height="180"></canvas><p class="info">Speed (lime) · throttle (white) · brake (orange). ${telemetry.length} samples at 10 Hz.<br>Latest sectors: ${lastSectors.length?lastSectors.map(formatTime).join(' / '):'Complete a lap to record sectors.'}</p><table class="telemetry-table"><tr><th>Tyre</th><th>Temp</th><th>Load</th><th>Brake</th><th>Wear</th></tr>${car.wheels.map((w,i)=>`<tr><td>${['FL','FR','RL','RR'][i]}</td><td>${w.temp.toFixed(0)} °C</td><td>${w.load.toFixed(0)} N</td><td>${w.brakeTemp.toFixed(0)} °C</td><td>${w.wear.toFixed(1)}%</td></tr>`).join('')}</table><div class="modal-actions"><button class="secondary" id="csv">DOWNLOAD CSV</button></div>`);let ctx=$('#telemetry-chart').getContext('2d');for(let [index,color,scale] of [[2,'#d5ff43',360],[6,'#f5f5e8',1],[7,'#ff7457',1]]){ctx.beginPath();telemetry.forEach((r,i)=>{let x=i/Math.max(1,telemetry.length-1)*640,y=175-r[index]/scale*165;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.stroke();}$('#csv').onclick=()=>{let text='time_s,distance_m,speed_kmh,rpm,gear,steer_rad,throttle,brake,ers_percent,deploy_kw,aero_open,downforce_n,fuel_kg,fl_temp_c,fr_temp_c,rl_temp_c,rr_temp_c\n'+telemetry.map(r=>r.join(',')).join('\n');downloadBlob(text,'apex-telemetry.csv','text/csv');};}
$('#telemetry-open').onclick=showTelemetry;
window.addEventListener('keydown',e=>{if(e.code==='KeyT'&&!e.repeat&&state==='race'){e.preventDefault();showTelemetry();}});
function downloadBlob(text,name,type){let url=URL.createObjectURL(new Blob([text],{type}));let a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#credits-open').onclick=()=>showModal('BUILT FOR THE LOVE OF RACING.','CREDITS & ACCURACY',`<p class="info">Original APEX LINE AL-02 procedural car, fictional branding, scenery and synthesized audio.<br><br>Three.js · MIT license · Three.js authors.<br>Circuit geographic outlines © 2019–2025 Tomislav Bacinger · MIT license.<br>Source: github.com/bacinger/f1-circuits<br><br>Map-derived planforms, not licensed official circuit replicas. Widths, flat terrain, structures and zone rules are game approximations. No affiliation with any championship, circuit operator or team.<br><br>Full licenses and limits are bundled in LICENSES.md and docs/REQUIREMENTS.md.</p>`);
$('#export-save').onclick=()=>{let layouts={};try{for(let i=0;i<localStorage.length;i++){let key=localStorage.key(i);if(key.startsWith('apex.layout.'))layouts[key]=JSON.parse(localStorage.getItem(key));}}catch{toast('Some local layouts could not be exported.')}downloadJSON({version:3,settings,bindings,records,layouts},'apex-save-v3.json');};
$('#import-save').onclick=()=>$('#save-file').click();$('#save-file').onchange=async e=>{try{let f=e.target.files[0];if(!f||f.size>500000)throw Error();let d=JSON.parse(await f.text());if(d.version!==3||!d.settings||!d.bindings||!d.records)throw Error();d.bindings={...defaultBindings,...d.bindings};for(let k in defaultBindings)if(!Array.isArray(d.bindings[k])||d.bindings[k].length>3||d.bindings[k].some(v=>typeof v!=='string'||!/^([A-Za-z0-9]+)$/.test(v)))throw Error();for(let [k,v]of Object.entries(d.settings)){if(!(k in defaults)||typeof v!==typeof defaults[k])throw Error();if(typeof v==='number'&&(!Number.isFinite(v)||Math.abs(v)>100))throw Error();}const enums={device:['keyboard','gamepad','touch','tilt'],quality:['low','medium','high','ultra'],assist:['casual','simulation','hardcore'],compound:['soft','medium','hard','inter','wet'],ersMode:['manual','off','harvest','balanced','attack'],steering:['buttons','wheel','slider'],transmission:['auto','manual'],display:['windowed','fullscreen','immersive','cinematic'],profile:['Default','Two-thumb','Left-hand dominant','Right-hand dominant','Sim','Custom 1','Custom 2']};for(let[k,values]of Object.entries(enums))if(k in d.settings&&!values.includes(d.settings[k]))throw Error();if(d.settings.color&&!/^#[a-f0-9]{6}$/i.test(d.settings.color))throw Error();const ranges={engineBraking:[0,1],setup:[0,1],startFuel:[5,100],brakeBias:[.48,.66],pressure:[18,28],rideHeight:[.035,.12],volume:[0,.5],sensitivity:[.4,1.5],deadzone:[0,.4],tiltSensitivity:[.3,2],tiltDeadzone:[0,12]};for(let[k,[lo,hi]]of Object.entries(ranges))if(k in d.settings&&(d.settings[k]<lo||d.settings[k]>hi))throw Error();for(let [k,v]of Object.entries(d.records))if(typeof v!=='number'||!Number.isFinite(v)||v<=0||k.length>150)throw Error();for(let [k,v]of Object.entries(d.layouts||{}))if(!k.startsWith('apex.layout.')||!validateLayout(v)||Object.keys(v).some(x=>!labels[x]))throw Error();settings={...defaults,...d.settings};bindings=d.bindings;records=d.records;store.set('settings',settings);store.set('bindings',bindings);store.set('records.v3',records);for(let[k,v]of Object.entries(d.layouts||{}))localStorage.setItem(k,JSON.stringify(v));applySettings();toast('Save imported. Start a new session.');}catch{toast('Invalid save; import rejected.')}};

if(['localhost','127.0.0.1'].includes(location.hostname))window.apexDebug.test={advance:(seconds,input)=>{for(let i=0;i<seconds*120;i++){let old=car.s;stepCar(car,input,1/120,{width:18,assist:settings.assist,setup:settings.setup,aeroZone:tracks[trackIndex].aeroZones.some(z=>car.s/length>=z.start&&car.s/length<=z.end),wet});projectCar(old)}animateModel(carModel,car,1/60);},pose:(distance,speed=0)=>{car.s=distance;resetPose();car.u=speed;car.v=speed;},rig:()=>carModel,road:()=>({samples:samples.map(a=>({p:[a.p.x,a.p.z],n:[a.normal.x,a.normal.z]})),footprints:sceneryFootprints}),input:()=>readInput(),action,profile:()=>raceProfile};
